In [39]:
import pandas as pd
import seaborn as sns

In [40]:
df = pd.read_excel('Online_Retail.xlsx')

In [11]:
df

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France

In [41]:
df.shape

(541909, 8)

In [18]:
print(df.isnull().sum())

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [42]:
df = df.dropna(subset=['CustomerID'])

In [43]:
df.shape

(406829, 8)

In [44]:
df.duplicated().sum()

np.int64(5225)

In [45]:
filas_duplicadas = df[df.duplicated(keep=False)].sort_values(by=['InvoiceNo', 'StockCode'])
print(filas_duplicadas.head(10))

    InvoiceNo StockCode                       Description  Quantity  \
494    536409     21866       UNION JACK FLAG LUGGAGE TAG         1
517    536409     21866       UNION JACK FLAG LUGGAGE TAG         1
485    536409     22111      SCOTTIE DOG HOT WATER BOTTLE         1
539    536409     22111      SCOTTIE DOG HOT WATER BOTTLE         1
489    536409     22866     HAND WARMER SCOTTY DOG DESIGN         1
527    536409     22866     HAND WARMER SCOTTY DOG DESIGN         1
521    536409     22900   SET 2 TEA TOWELS I LOVE LONDON          1
537    536409     22900   SET 2 TEA TOWELS I LOVE LONDON          1
565    536412     21448         12 DAISY PEGS IN WOOD BOX         2
578    536412     21448         12 DAISY PEGS IN WOOD BOX         1

            InvoiceDate  UnitPrice  CustomerID         Country
494 2010-12-01 11:45:00       1.25     17908.0  United Kingdom
517 2010-12-01 11:45:00       1.25     17908.0  United Kingdom
485 2010-12-01 11:45:00       4.95     17908.0  United Kingdom
539 2010-12-01 11:45:00       4.95     17908.0  United Kingdom
489 2010-12-01 11:45:00       2.10     17908.0  United Kingdom
527 2010-12-01 11:45:00       2.10     17908.0  United Kingdom
521 2010-12-01 11:45:00       2.95     17908.0  United Kingdom
537 2010-12-01 11:45:00       2.95     17908.0  United Kingdom
565 2010-12-01 11:49:00       1.65     17920.0  United Kingdom
578 2010-12-01 11:49:00       1.65     17920.0  United Kingdom

In [46]:
df = df.drop_duplicates()

In [47]:
df.shape

(401604, 8)

In [27]:
df.describe()

            Quantity                 InvoiceDate      UnitPrice     CustomerID
count  401604.000000                      401604  401604.000000  401604.000000
mean       12.183273  2011-07-10 12:08:23.848567       3.474064   15281.160818
min    -80995.000000         2010-12-01 08:26:00       0.000000   12346.000000
25%         2.000000         2011-04-06 15:02:00       1.250000   13939.000000
50%         5.000000         2011-07-29 15:40:00       1.950000   15145.000000
75%        12.000000         2011-10-20 11:58:30       3.750000   16784.000000
max     80995.000000         2011-12-09 12:50:00   38970.000000   18287.000000
std       250.283037                         NaN      69.764035    1714.006089

In [32]:
cantidad_negativos = (df['Quantity'] < 0).sum()
print(f'Hay {cantidad_negativos} filas con cantidades negativas.')

Hay 8872 filas con cantidades negativas.

In [38]:
df.dtypes

InvoiceNo              object
StockCode              object
Description            object
Quantity                int64
InvoiceDate    datetime64[us]
UnitPrice             float64
CustomerID            float64
Country                   str
dtype: object

In [51]:
df['CustomerID'] = df['CustomerID'].astype(str)

In [53]:
df.dtypes

InvoiceNo              object
StockCode              object
Description            object
Quantity                int64
InvoiceDate    datetime64[us]
UnitPrice             float64
CustomerID                str
Country                   str
dtype: object